//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.15 at 04:16:28 PM PST 
//


package com.per_colator.percolator_out._13;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.yeastrc.proteomics.percolator.out.perc_out_common_interfaces.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="command_line" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="other_command_line" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pi_0_psms" type="{http://per-colator.com/percolator_out/13}probability_t" minOccurs="0"/>
 *         &lt;element name="pi_0_peptides" type="{http://per-colator.com/percolator_out/13}probability_t" minOccurs="0"/>
 *         &lt;element name="pi_0_proteins" type="{http://per-colator.com/percolator_out/13}probability_t" minOccurs="0"/>
 *         &lt;element name="average_delta_mass" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="average_pi" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="comment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commandLine",
    "otherCommandLine",
    "pi0Psms",
    "pi0Peptides",
    "pi0Proteins",
    "averageDeltaMass",
    "averagePi",
    "comment"
})
@XmlRootElement(name = "process_info")
public class ProcessInfo implements IProcessInfo {

    @XmlElement(name = "command_line", required = true)
    protected String commandLine;
    @XmlElement(name = "other_command_line", required = true)
    protected String otherCommandLine;
    @XmlElement(name = "pi_0_psms")
    protected String pi0Psms;
    @XmlElement(name = "pi_0_peptides")
    protected String pi0Peptides;
    @XmlElement(name = "pi_0_proteins")
    protected String pi0Proteins;
    @XmlElement(name = "average_delta_mass")
    protected Double averageDeltaMass;
    @XmlElement(name = "average_pi")
    protected Double averagePi;
    protected List<ProcessInfo.Comment> comment;

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProcessInfo#getCommandLine()
	 */
    @Override
	public String getCommandLine() {
        return commandLine;
    }

    /**
     * Sets the value of the commandLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandLine(String value) {
        this.commandLine = value;
    }

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProcessInfo#getOtherCommandLine()
	 */
    @Override
	public String getOtherCommandLine() {
        return otherCommandLine;
    }

    /**
     * Sets the value of the otherCommandLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherCommandLine(String value) {
        this.otherCommandLine = value;
    }

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProcessInfo#getPi0Psms()
	 */
    @Override
	public String getPi0Psms() {
        return pi0Psms;
    }

    /**
     * Sets the value of the pi0Psms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPi0Psms(String value) {
        this.pi0Psms = value;
    }

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProcessInfo#getPi0Peptides()
	 */
    @Override
	public String getPi0Peptides() {
        return pi0Peptides;
    }

    /**
     * Sets the value of the pi0Peptides property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPi0Peptides(String value) {
        this.pi0Peptides = value;
    }

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProcessInfo#getPi0Proteins()
	 */
    @Override
	public String getPi0Proteins() {
        return pi0Proteins;
    }

    /**
     * Sets the value of the pi0Proteins property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPi0Proteins(String value) {
        this.pi0Proteins = value;
    }

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProcessInfo#getAverageDeltaMass()
	 */
    @Override
	public Double getAverageDeltaMass() {
        return averageDeltaMass;
    }

    /**
     * Sets the value of the averageDeltaMass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAverageDeltaMass(Double value) {
        this.averageDeltaMass = value;
    }

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProcessInfo#getAveragePi()
	 */
    @Override
	public Double getAveragePi() {
        return averagePi;
    }

    /**
     * Sets the value of the averagePi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAveragePi(Double value) {
        this.averagePi = value;
    }

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProcessInfo#getComment()
	 */
    @Override
	public List<ProcessInfo.Comment> getComment() {
        if (comment == null) {
            comment = new ArrayList<ProcessInfo.Comment>();
        }
        return this.comment;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Comment implements IProcessInfo_Comment {

        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "value", required = true)
        protected String value;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
