//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.15 at 04:16:28 PM PST 
//


package com.per_colator.percolator_out._13;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.yeastrc.proteomics.percolator.out.perc_out_common_interfaces.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://per-colator.com/percolator_out/13}pep" minOccurs="0"/>
 *         &lt;element ref="{http://per-colator.com/percolator_out/13}q_value"/>
 *         &lt;element ref="{http://per-colator.com/percolator_out/13}peptide_seq" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://per-colator.com/percolator_out/13}protein_id use="required""/>
 *       &lt;attribute ref="{http://per-colator.com/percolator_out/13}decoy"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pep",
    "qValue",
    "peptideSeq"
})
@XmlRootElement(name = "protein")
public class Protein implements IProtein {

    protected String pep;
    @XmlElement(name = "q_value", required = true)
    protected String qValue;
    @XmlElement(name = "peptide_seq", required = true)
    protected List<PeptideSeq> peptideSeq;
    @XmlAttribute(name = "protein_id", namespace = "http://per-colator.com/percolator_out/13", required = true)
    protected String proteinId;
    @XmlAttribute(name = "decoy", namespace = "http://per-colator.com/percolator_out/13")
    protected Boolean decoy;

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProtein#getPep()
	 */
    @Override
	public String getPep() {
        return pep;
    }

    /**
     * Sets the value of the pep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPep(String value) {
        this.pep = value;
    }

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProtein#getQValue()
	 */
    @Override
	public String getQValue() {
        return qValue;
    }

    /**
     * Sets the value of the qValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQValue(String value) {
        this.qValue = value;
    }

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProtein#getPeptideSeq()
	 */
    @Override
	public List<PeptideSeq> getPeptideSeq() {
        if (peptideSeq == null) {
            peptideSeq = new ArrayList<PeptideSeq>();
        }
        return this.peptideSeq;
    }

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProtein#getProteinId()
	 */
    @Override
	public String getProteinId() {
        return proteinId;
    }

    /**
     * Sets the value of the proteinId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProteinId(String value) {
        this.proteinId = value;
    }

    /* (non-Javadoc)
	 * @see com.per_colator.percolator_out._13.IProtein#isDecoy()
	 */
    @Override
	public Boolean isDecoy() {
        return decoy;
    }

    /**
     * Sets the value of the decoy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDecoy(Boolean value) {
        this.decoy = value;
    }

}
