//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.15 at 04:16:28 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://per-colator.com/percolator_out/13", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.per_colator.percolator_out._13;
