//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.05 at 12:12:28 PM PDT 
//


package com.per_colator.percolator_out._14;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.yeastrc.proteomics.percolator.out.perc_out_common_interfaces.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="command_line" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="other_command_line" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pi_0_psms" type="{http://per-colator.com/percolator_out/14}probability_t" minOccurs="0"/>
 *         &lt;element name="pi_0_peptides" type="{http://per-colator.com/percolator_out/14}probability_t" minOccurs="0"/>
 *         &lt;element name="pi_0_proteins" type="{http://per-colator.com/percolator_out/14}probability_t" minOccurs="0"/>
 *         &lt;element name="fdr_proteins" type="{http://per-colator.com/percolator_out/14}probability_t" minOccurs="0"/>
 *         &lt;element name="alpha" type="{http://per-colator.com/percolator_out/14}probability_t" minOccurs="0"/>
 *         &lt;element name="beta" type="{http://per-colator.com/percolator_out/14}probability_t" minOccurs="0"/>
 *         &lt;element name="gamma" type="{http://per-colator.com/percolator_out/14}probability_t" minOccurs="0"/>
 *         &lt;element name="psms_qlevel" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="peptides_qlevel" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="proteins_qlevel" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="average_delta_mass" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="average_pi" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="comment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commandLine",
    "otherCommandLine",
    "pi0Psms",
    "pi0Peptides",
    "pi0Proteins",
    "fdrProteins",
    "alpha",
    "beta",
    "gamma",
    "psmsQlevel",
    "peptidesQlevel",
    "proteinsQlevel",
    "averageDeltaMass",
    "averagePi",
    "comment"
})
@XmlRootElement(name = "process_info")
public class ProcessInfo implements IProcessInfo {

    @XmlElement(name = "command_line", required = true)
    protected String commandLine;
    @XmlElement(name = "other_command_line", required = true)
    protected String otherCommandLine;
    @XmlElement(name = "pi_0_psms")
    protected String pi0Psms;
    @XmlElement(name = "pi_0_peptides")
    protected String pi0Peptides;
    @XmlElement(name = "pi_0_proteins")
    protected String pi0Proteins;
    @XmlElement(name = "fdr_proteins")
    protected String fdrProteins;
    protected String alpha;
    protected String beta;
    protected String gamma;
    @XmlElement(name = "psms_qlevel")
    protected Double psmsQlevel;
    @XmlElement(name = "peptides_qlevel")
    protected Double peptidesQlevel;
    @XmlElement(name = "proteins_qlevel")
    protected Double proteinsQlevel;
    @XmlElement(name = "average_delta_mass")
    protected Double averageDeltaMass;
    @XmlElement(name = "average_pi")
    protected Double averagePi;
    protected List<ProcessInfo.Comment> comment;

    /**
     * Gets the value of the commandLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommandLine() {
        return commandLine;
    }

    /**
     * Sets the value of the commandLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandLine(String value) {
        this.commandLine = value;
    }

    /**
     * Gets the value of the otherCommandLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherCommandLine() {
        return otherCommandLine;
    }

    /**
     * Sets the value of the otherCommandLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherCommandLine(String value) {
        this.otherCommandLine = value;
    }

    /**
     * Gets the value of the pi0Psms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPi0Psms() {
        return pi0Psms;
    }

    /**
     * Sets the value of the pi0Psms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPi0Psms(String value) {
        this.pi0Psms = value;
    }

    /**
     * Gets the value of the pi0Peptides property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPi0Peptides() {
        return pi0Peptides;
    }

    /**
     * Sets the value of the pi0Peptides property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPi0Peptides(String value) {
        this.pi0Peptides = value;
    }

    /**
     * Gets the value of the pi0Proteins property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPi0Proteins() {
        return pi0Proteins;
    }

    /**
     * Sets the value of the pi0Proteins property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPi0Proteins(String value) {
        this.pi0Proteins = value;
    }

    /**
     * Gets the value of the fdrProteins property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFdrProteins() {
        return fdrProteins;
    }

    /**
     * Sets the value of the fdrProteins property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFdrProteins(String value) {
        this.fdrProteins = value;
    }

    /**
     * Gets the value of the alpha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlpha() {
        return alpha;
    }

    /**
     * Sets the value of the alpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlpha(String value) {
        this.alpha = value;
    }

    /**
     * Gets the value of the beta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeta() {
        return beta;
    }

    /**
     * Sets the value of the beta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeta(String value) {
        this.beta = value;
    }

    /**
     * Gets the value of the gamma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGamma() {
        return gamma;
    }

    /**
     * Sets the value of the gamma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGamma(String value) {
        this.gamma = value;
    }

    /**
     * Gets the value of the psmsQlevel property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPsmsQlevel() {
        return psmsQlevel;
    }

    /**
     * Sets the value of the psmsQlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPsmsQlevel(Double value) {
        this.psmsQlevel = value;
    }

    /**
     * Gets the value of the peptidesQlevel property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPeptidesQlevel() {
        return peptidesQlevel;
    }

    /**
     * Sets the value of the peptidesQlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPeptidesQlevel(Double value) {
        this.peptidesQlevel = value;
    }

    /**
     * Gets the value of the proteinsQlevel property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getProteinsQlevel() {
        return proteinsQlevel;
    }

    /**
     * Sets the value of the proteinsQlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setProteinsQlevel(Double value) {
        this.proteinsQlevel = value;
    }

    /**
     * Gets the value of the averageDeltaMass property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAverageDeltaMass() {
        return averageDeltaMass;
    }

    /**
     * Sets the value of the averageDeltaMass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAverageDeltaMass(Double value) {
        this.averageDeltaMass = value;
    }

    /**
     * Gets the value of the averagePi property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAveragePi() {
        return averagePi;
    }

    /**
     * Sets the value of the averagePi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAveragePi(Double value) {
        this.averagePi = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessInfo.Comment }
     * 
     * 
     */
    public List<ProcessInfo.Comment> getComment() {
        if (comment == null) {
            comment = new ArrayList<ProcessInfo.Comment>();
        }
        return this.comment;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Comment implements IProcessInfo_Comment {

        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "value", required = true)
        protected String value;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
