//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.03 at 04:03:59 PM PDT 
//


package com.per_colator.percolator_in._12;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.per_colator.percolator_in._12 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.per_colator.percolator_in._12
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Experiment }
     * 
     */
    public Experiment createExperiment() {
        return new Experiment();
    }

    /**
     * Create an instance of {@link ModificationType }
     * 
     */
    public ModificationType createModificationType() {
        return new ModificationType();
    }

    /**
     * Create an instance of {@link Experiment.Proteins }
     * 
     */
    public Experiment.Proteins createExperimentProteins() {
        return new Experiment.Proteins();
    }

    /**
     * Create an instance of {@link Experiment.FragSpectrumScan }
     * 
     */
    public Experiment.FragSpectrumScan createExperimentFragSpectrumScan() {
        return new Experiment.FragSpectrumScan();
    }

    /**
     * Create an instance of {@link Experiment.FragSpectrumScan.PeptideSpectrumMatch }
     * 
     */
    public Experiment.FragSpectrumScan.PeptideSpectrumMatch createExperimentFragSpectrumScanPeptideSpectrumMatch() {
        return new Experiment.FragSpectrumScan.PeptideSpectrumMatch();
    }

    /**
     * Create an instance of {@link Experiment.FeatureDescriptions }
     * 
     */
    public Experiment.FeatureDescriptions createExperimentFeatureDescriptions() {
        return new Experiment.FeatureDescriptions();
    }

    /**
     * Create an instance of {@link Experiment.Calibration }
     * 
     */
    public Experiment.Calibration createExperimentCalibration() {
        return new Experiment.Calibration();
    }

    /**
     * Create an instance of {@link Experiment.Databases }
     * 
     */
    public Experiment.Databases createExperimentDatabases() {
        return new Experiment.Databases();
    }

    /**
     * Create an instance of {@link Experiment.FreeTextInformation }
     * 
     */
    public Experiment.FreeTextInformation createExperimentFreeTextInformation() {
        return new Experiment.FreeTextInformation();
    }

    /**
     * Create an instance of {@link Experiment.ProcessInfo }
     * 
     */
    public Experiment.ProcessInfo createExperimentProcessInfo() {
        return new Experiment.ProcessInfo();
    }

    /**
     * Create an instance of {@link PeptideType }
     * 
     */
    public PeptideType createPeptideType() {
        return new PeptideType();
    }

    /**
     * Create an instance of {@link ModificationType.UniMod }
     * 
     */
    public ModificationType.UniMod createModificationTypeUniMod() {
        return new ModificationType.UniMod();
    }

    /**
     * Create an instance of {@link Experiment.Proteins.Protein }
     * 
     */
    public Experiment.Proteins.Protein createExperimentProteinsProtein() {
        return new Experiment.Proteins.Protein();
    }

    /**
     * Create an instance of {@link Experiment.FragSpectrumScan.PeptideSpectrumMatch.Features }
     * 
     */
    public Experiment.FragSpectrumScan.PeptideSpectrumMatch.Features createExperimentFragSpectrumScanPeptideSpectrumMatchFeatures() {
        return new Experiment.FragSpectrumScan.PeptideSpectrumMatch.Features();
    }

    /**
     * Create an instance of {@link Experiment.FragSpectrumScan.PeptideSpectrumMatch.Occurence }
     * 
     */
    public Experiment.FragSpectrumScan.PeptideSpectrumMatch.Occurence createExperimentFragSpectrumScanPeptideSpectrumMatchOccurence() {
        return new Experiment.FragSpectrumScan.PeptideSpectrumMatch.Occurence();
    }

    /**
     * Create an instance of {@link Experiment.FeatureDescriptions.FeatureDescription }
     * 
     */
    public Experiment.FeatureDescriptions.FeatureDescription createExperimentFeatureDescriptionsFeatureDescription() {
        return new Experiment.FeatureDescriptions.FeatureDescription();
    }

    /**
     * Create an instance of {@link Experiment.Calibration.CalibrationParameter }
     * 
     */
    public Experiment.Calibration.CalibrationParameter createExperimentCalibrationCalibrationParameter() {
        return new Experiment.Calibration.CalibrationParameter();
    }

    /**
     * Create an instance of {@link Experiment.Databases.Parameters }
     * 
     */
    public Experiment.Databases.Parameters createExperimentDatabasesParameters() {
        return new Experiment.Databases.Parameters();
    }

}
